"""empty message

Revision ID: 11ddd75a4034
Revises: a56eb0f88d08
Create Date: 2022-08-07 22:47:25.294115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ddd75a4034'
down_revision = 'a56eb0f88d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('id_editorial', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'book', 'editorial', ['id_editorial'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'id_editorial')
    op.drop_table('editorial')
    # ### end Alembic commands ###
