"""empty message

Revision ID: 68152efb549c
Revises: 5c34faeea863
Create Date: 2022-08-07 23:26:05.032691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68152efb549c'
down_revision = '5c34faeea863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_tags',
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['book.id'], ),
    sa.ForeignKeyConstraint(['id_tag'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id_tag', 'id_book')
    )
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id_tag', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_book', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['book.id'], name='tags_ibfk_1'),
    sa.ForeignKeyConstraint(['id_tag'], ['tag.id'], name='tags_ibfk_2'),
    sa.PrimaryKeyConstraint('id_tag', 'id_book'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('books_tags')
    # ### end Alembic commands ###
