"""empty message

Revision ID: ab8d661b4728
Revises: 2f3143ca16e9
Create Date: 2022-08-07 18:07:37.773083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab8d661b4728'
down_revision = '2f3143ca16e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'name')
    op.add_column('book', sa.Column('id_author', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'book', 'author', ['id_author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'id_author')
    op.add_column('author', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
