"""empty message

Revision ID: abfd49079cd8
Revises: 5f7d46cc782b
Create Date: 2023-06-28 20:38:15.454808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abfd49079cd8'
down_revision = '5f7d46cc782b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('review', sa.Text(), nullable=True))
    op.drop_column('book', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_column('book', 'review')
    # ### end Alembic commands ###
