"""empty message

Revision ID: b9d22c840958
Revises: 68152efb549c
Create Date: 2022-08-07 23:27:11.651513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d22c840958'
down_revision = '68152efb549c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###
